---
- name: Copy a new Zabbix Proxy config with our variables
  ansible.builtin.template:
    src: zabbix_proxy.conf.j2
    dest: /etc/zabbix/zabbix_proxy.conf
    mode: '0640'
    owner: root
    group: root
  notify:
    - Restart zabbix-proxy service

- name: Create directory for Zabbix external scripts
  ansible.builtin.file:
    path: /usr/lib/zabbix/externalscripts
    state: directory
    mode: '0755'
    owner: zabbix
    group: zabbix

- name: Copy Zabbix external script for Nginx stats
  ansible.builtin.copy:
    src: nginx-stats.sh
    dest: /usr/lib/zabbix/externalscripts/nginx-stats.sh
    mode: '0755'
    owner: zabbix
    group: zabbix
  notify:
    - Restart zabbix-proxy service

- name: Install Zabbix MySQL scripts
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - zabbix-sql-scripts
  environment:
    DEBIAN_FRONTEND: noninteractive
  notify:
    - Restart zabbix-proxy service

- name: Create MySQL database for Zabbix Proxy
  community.mysql.mysql_db:
    name: "{{ zabbix_proxy_dbname }}"
    state: present
  notify:
    - Import schema to zabbix-proxy database

- name: Create the database user for Zabbix Proxy DB
  no_log: true
  community.mysql.mysql_user:
    name: "{{ zabbix_proxy_dbuser }}"
    password: "{{ zabbix_proxy_dbpass }}"
    priv: "{{ zabbix_proxy_dbname }}.*:ALL"
    host: localhost
    state: present

- name: Add psk key for Zabbix Proxy
  when: zabbix_proxy_psk is defined
  ansible.builtin.template:
    src: proxy.psk.j2
    dest: /etc/zabbix/proxy.psk
    mode: '0640'
    owner: root
    group: root
  notify:
    - Restart zabbix-proxy service
