---
- name: Import schema to zabbix-proxy database
  community.mysql.mysql_db:
    name: "{{ zabbix_proxy_dbname }}"
    state: import
    target: /usr/share/doc/zabbix-sql-scripts/mysql/schema.sql.gz
    force: true

- name: Enable zabbix-proxy service
  ansible.builtin.service:
    name: zabbix-proxy
    enabled: true

- name: Restart zabbix-proxy service
  ansible.builtin.service:
    name: zabbix-proxy
    state: restarted
