---
- name: Converge
  hosts: all
  tasks:
    - name: Install requirements
      ansible.builtin.apt:
        name: gnupg
        state: present
        update_cache: true
    - name: "Dependency role for MySQL Server"
      ansible.builtin.include_role:
        name: "leadlineit.mysql_server"
    - name: "Include leadlineit.zabbix_proxy"
      ansible.builtin.include_role:
        name: "leadlineit.zabbix_proxy"
